---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

require:
- rubocop-performance

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: no

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  Max: 120

Style:
  Severity: warning

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/PreferredHashMethods:
  EnforcedStyle: verbose
