---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: no

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  Max: 120

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec:
  Severity: warning

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Style:
  Severity: warning

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/PreferredHashMethods:
  EnforcedStyle: verbose
